import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from 'next/link';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body>
        <nav className="flex justify-around bg-gray-800 text-white p-4">
            <h1 className="text-lg">My Finance App</h1>
            <div>
                <Link href="#" className="mx-2">About</Link>
                <Link href="#" className="mx-2">Help</Link>
                <Link href="#" className="mx-2">Info</Link>
                <Link href="#" className="mx-2">Helpline</Link>
            </div>
        </nav>
        <div className="p-4">
            {children}
        </div>
    </body>
</html>
  );
}
